server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: backer
    password: backer
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /vhosts_backer

    listener:
      simple:
        #设置消费端手动 ack
        acknowledge-mode: manual
        #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 2
      #消费者最小数量
      concurrency: 1
      #消费之最大数量
      max-concurrency: 101

logging:
  level:
    root: debug